//
//  SurveyPurposePresenter.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2021/1/3.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SurveyPurposePresentationLogic {
    // func presentSomething(response: SurveyPurpose.Something.Response)
}

class SurveyPurposePresenter: SurveyPurposePresentationLogic {
    
    weak var viewController: SurveyPurposeDisplayLogic?
    
    // MARK: Presenter Methods

    // func presentSomething(response: SurveyPurpose.Something.Response) {
    //     let viewModel = SurveyPurpose.Something.ViewModel()
    //     viewController?.displaySomething(viewModel: viewModel)
    // }

}
