//
//  SurveyPurposeRouter.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2021/1/3.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SurveyPurposeRoutingNavigation {
    func showNewScreen()
}

protocol SurveyPurposeDataPassing {
    var dataStore: SurveyPurposeDataStore? { get set }
}

typealias SurveyPurposeRouterInput = SurveyPurposeRoutingNavigation & SurveyPurposeDataPassing

class SurveyPurposeRouter: SurveyPurposeRouterInput {
    
    var dataStore: SurveyPurposeDataStore?
    weak var viewController: SurveyPurposeViewController?
    
    // MARK: Navigation
    
    func showNewScreen() {
        
    }

}
