//
//  OrderViewController.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2021/1/8.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OrderDisplayLogic: class {
    func displaySomething(viewModel: Order.Something.ViewModel)
}

class OrderViewController: UIViewController, OrderDisplayLogic {
    
    // MARK: - Properties
    var interactor: OrderBusinessLogic?
    var router: OrderRouterInput?
    
    // Mark: - Outlets
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        OrderConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: - Do something
    
    func doSomething() {
        
    }
    
    func displaySomething(viewModel: Order.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
