//
//  testTemletInteractor.swift
//  ThirdWeekTest
//
//  Created by Xiaobei Zhu on 2020/12/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol testTemletBusinessLogic {
    // func doSomething(request: testTemlet.Something.Request)    
}

protocol testTemletDataStore {
    // var name: String { get set }
}

class testTemletInteractor: testTemletBusinessLogic, testTemletDataStore {
    
    var presenter: testTemletPresentationLogic?
    lazy var worker: testTemletWorker? = {
        return testTemletWorker()
    }()
    
    // MARK: Interactor Methods

    // func doSomething(request: testTemlet.Something.Request) {
    //     worker = testTemletWorker()
    //     worker?.doSomeWork()
        
    //     let response = testTemlet.Something.Response()
    //     presenter?.presentSomething(response: response)
    // }

}
