//
//  testTemletRouter.swift
//  ThirdWeekTest
//
//  Created by Xiaobei Zhu on 2020/12/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol testTemletRoutingNavigation {
    func showNewScreen()
}

protocol testTemletDataPassing {
    var dataStore: testTemletDataStore? { get set }
}

typealias testTemletRouterInput = testTemletRoutingNavigation & testTemletDataPassing

class testTemletRouter: testTemletRouterInput {
    
    var dataStore: testTemletDataStore?
    weak var viewController: testTemletViewController?
    
    // MARK: Navigation
    
    func showNewScreen() {
        
    }

}
