//
//  testTemletPresenter.swift
//  ThirdWeekTest
//
//  Created by Xiaobei Zhu on 2020/12/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol testTemletPresentationLogic {
    // func presentSomething(response: testTemlet.Something.Response)
}

class testTemletPresenter: testTemletPresentationLogic {
    
    weak var viewController: testTemletDisplayLogic?
    
    // MARK: Presenter Methods

    // func presentSomething(response: testTemlet.Something.Response) {
    //     let viewModel = testTemlet.Something.ViewModel()
    //     viewController?.displaySomething(viewModel: viewModel)
    // }

}
