//
//  testTemletConfigurator.swift
//  ThirdWeekTest
//
//  Created by Xiaobei Zhu on 2020/12/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Connects View, Interactor, and Presenter
class testTemletConfigurator {
    
    static let sharedInstance = testTemletConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(_ viewController: testTemletViewController) {
        let presenter = testTemletPresenter()
        presenter.viewController = viewController
        
        let interactor = testTemletInteractor()
        interactor.presenter = presenter
        
        let router = testTemletRouter()
        router.viewController = viewController
        router.dataStore = interactor
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
