//
//  SignUpWithEmailPresenter.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpWithEmailPresentationLogic {
    // func presentSomething(response: SignUpWithEmail.Something.Response)
    func presenterEmailPasswordVerify(response: Verification.VerifyEmailPassword.Response)
}

class SignUpWithEmailPresenter: SignUpWithEmailPresentationLogic {
    
    weak var viewController: SignUpWithEmailDisplayLogic?
    
    // MARK: Presenter Methods
    
    func presenterEmailPasswordVerify(response: Verification.VerifyEmailPassword.Response) {
        switch response {
        case .emailHint:
            let emailHintresult = "You will need verify this email address shortly."
            viewController?.displayEmailHintMessage(result: emailHintresult)
        case .passwordHint(result: let passwordHintMessage):
        viewController?.displayPasswordHintMessage(result: passwordHintMessage.toHintAttributedText())
        case .errorMessage(emailMessage: let emailMessage, passwordMessage: let passwordMessage):
            viewController?.displayEmailMessage(result: emailMessage)
            viewController?.displayPasswordMessage(result: passwordMessage)
        case .noMessage:
            viewController?.displayNoMessage()
        case .good:
            viewController?.displayGood()
        
        }
    }


}
