//
//  SignUpWithEmailModels.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Verification {
    // MARK: Use cases
    enum VerifyEmailPassword {

        struct Request {
            let isEmailEntering: Bool
            let emailAddress: String
            let isPasswordEntering: Bool
            let password: String
        }

        enum Response {
            case emailHint
            case passwordHint(result: PasswordValidationResult)
            case errorMessage(emailMessage: String, passwordMessage:String)
            case good
            case noMessage

        struct ViewModel {
        
        }    
    }
    
    }
}
