//
//  SignUpWithEmailConfigurator.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/28.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Connects View, Interactor, and Presenter
class SignUpWithEmailConfigurator {
    
    static let sharedInstance = SignUpWithEmailConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(_ viewController: SignUpWithEmailViewController) {
        let presenter = SignUpWithEmailPresenter()
        presenter.viewController = viewController
        
        let interactor = SignUpWithEmailInteractor()
        interactor.presenter = presenter
        
        let router = SignUpWithEmailRouter()
        router.viewController = viewController
        router.dataStore = interactor
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
