//
//  SearchPresenter.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2021/1/3.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presenterCountries(response: [[String: String]])
}

class SearchPresenter: SearchPresentationLogic {
   
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Presenter Methods

    // func presentSomething(response: Search.Something.Response) {
    //     let viewModel = Search.Something.ViewModel()
    //     viewController?.displaySomething(viewModel: viewModel)
    // }

    func presenterCountries(response: [[String : String]]){
        viewController?.displayCountryInformation(viewModel: Search.SearchCountry.ViewModel(countryInformationDic: response))
    }
}
