//
//  SearchWorker.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2021/1/3.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol SearchWorkerLogic {
    
}
class SearchWorker {
//    MockServer;.sharedInstance.getCountry() { country in
//
//    }
//   Load country data
    func getCountryData(_ completion: @escaping ([[String: String]]) -> Void) {
        let countrySharedInstance = MockServer.sharedInstance
        countrySharedInstance.getCountry(completion)
    }
    
}
