//
//  SearchModels.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2021/1/3.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search {
    // MARK: Use cases

    enum SearchCountry {

        struct Request {
           
        }

        struct Response {
            var countryInformatinDict: [String: String]?
        }

        struct ViewModel {
            var countryInformationDic: [[String: String]]
        }    
    }
}

