//
//  SearchInteractor.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2021/1/3.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic {
    // func doSomething(request: Search.Something.Request)
    func getCountryInformation(request: Search.SearchCountry.Request)
}

protocol SearchDataStore {
    // var name: String { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore {
    
    var presenter: SearchPresentationLogic?
    lazy var worker: SearchWorker? = {
        return SearchWorker()
    }()
    
    // MARK: Interactor Methods

    func getCountryInformation(request: Search.SearchCountry.Request) {
        worker?.getCountryData({ [self](countries) in
            presenter?.presenterCountries(response: countries)
        })

     }

}
