//
//  OptionalSurveyRouter.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/31.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OptionalSurveyRoutingNavigation {
    func showNewScreen()
}

protocol OptionalSurveyDataPassing {
    var dataStore: OptionalSurveyDataStore? { get set }
}

typealias OptionalSurveyRouterInput = OptionalSurveyRoutingNavigation & OptionalSurveyDataPassing

class OptionalSurveyRouter: OptionalSurveyRouterInput {
    
    var dataStore: OptionalSurveyDataStore?
    weak var viewController: OptionalSurveyViewController?
    
    // MARK: Navigation
    
    func showNewScreen() {
        
    }

}
