//
//  OptionalSurveyInteractor.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/31.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OptionalSurveyBusinessLogic {
    // func doSomething(request: OptionalSurvey.Something.Request)    
}

protocol OptionalSurveyDataStore {
    // var name: String { get set }
}

class OptionalSurveyInteractor: OptionalSurveyBusinessLogic, OptionalSurveyDataStore {
    
    var presenter: OptionalSurveyPresentationLogic?
    lazy var worker: OptionalSurveyWorker? = {
        return OptionalSurveyWorker()
    }()
    
    // MARK: Interactor Methods

    // func doSomething(request: OptionalSurvey.Something.Request) {
    //     worker = OptionalSurveyWorker()
    //     worker?.doSomeWork()
        
    //     let response = OptionalSurvey.Something.Response()
    //     presenter?.presentSomething(response: response)
    // }

}
