//
//  OptionalSurveyPresenter.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/31.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OptionalSurveyPresentationLogic {
    // func presentSomething(response: OptionalSurvey.Something.Response)
}

class OptionalSurveyPresenter: OptionalSurveyPresentationLogic {
    
    weak var viewController: OptionalSurveyDisplayLogic?
    
    // MARK: Presenter Methods

    // func presentSomething(response: OptionalSurvey.Something.Response) {
    //     let viewModel = OptionalSurvey.Something.ViewModel()
    //     viewController?.displaySomething(viewModel: viewModel)
    // }

}
