//
//  OptionalSurveyConfigurator.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/31.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - Connects View, Interactor, and Presenter
class OptionalSurveyConfigurator {
    
    static let sharedInstance = OptionalSurveyConfigurator()
    
    private init() {}
    
    // MARK: - Configuration
    
    func configure(_ viewController: OptionalSurveyViewController) {
        let presenter = OptionalSurveyPresenter()
        presenter.viewController = viewController
        
        let interactor = OptionalSurveyInteractor()
        interactor.presenter = presenter
        
        let router = OptionalSurveyRouter()
        router.viewController = viewController
        router.dataStore = interactor
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
