//
//  CountryInteractor.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2021/1/6.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryBusinessLogic {
    func countryInformation(request: Country.CountryInformationDetail.Request)
}

protocol CountryDataStore {
    var countryInformationDetail: [String: String] { get set }
}

class CountryInteractor: CountryBusinessLogic, CountryDataStore {
    var countryInformationDetail: [String : String] = [:]
    
    var presenter: CountryPresentationLogic?
    lazy var worker: CountryWorker? = {
        return CountryWorker()
    }()
    
    // MARK: Interactor Methods
    func countryInformation(request: Country.CountryInformationDetail.Request) {
        let countryName = countryInformationDetail["countryName"]!
        worker?.requestCountryInformation(countryName: countryName, {(country) in
            self.presenter?.presentCountryInformation(response: country)
        })
    }
   

}
