//
//  CountryModels.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2021/1/6.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Country {
    // MARK: Use cases

    enum CountryInformationDetail {

        struct Request {

        }

        struct Response {
            var countryDetail: [String:[String: Int]]
        
        }

        struct ViewModel {
            var countryDetail: [String:[String: Int]]

        }    
    }
}
