//
//  EmailConpletePresenter.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/25.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmailConpletePresentationLogic {
    // func presentSomething(response: EmailConplete.Something.Response)
}

class EmailConpletePresenter: EmailConpletePresentationLogic {
    
    weak var viewController: EmailConpleteDisplayLogic?
    
    // MARK: Presenter Methods

    // func presentSomething(response: EmailConplete.Something.Response) {
    //     let viewModel = EmailConplete.Something.ViewModel()
    //     viewController?.displaySomething(viewModel: viewModel)
    // }

}
