//
//  EmailConpleteViewController.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/25.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmailConpleteDisplayLogic: class {
    func displaySomething(viewModel: EmailConplete.Something.ViewModel)
}

class EmailConpleteViewController: UIViewController, EmailConpleteDisplayLogic {
    
    // MARK: - Properties
    var interactor: EmailConpleteBusinessLogic?
    var router: EmailConpleteRouterInput?
    
    // Mark: - Outlets
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    // MARK: - Object Lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        EmailConpleteConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: - Do something
    
    func doSomething() {
        
    }
    
    func displaySomething(viewModel: EmailConplete.Something.ViewModel) {
        //nameTextField.text = viewModel.name
    }
}
