//
//  qqqqPresenter.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/25.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol qqqqPresentationLogic {
    // func presentSomething(response: qqqq.Something.Response)
}

class qqqqPresenter: qqqqPresentationLogic {
    
    weak var viewController: qqqqDisplayLogic?
    
    // MARK: Presenter Methods

    // func presentSomething(response: qqqq.Something.Response) {
    //     let viewModel = qqqq.Something.ViewModel()
    //     viewController?.displaySomething(viewModel: viewModel)
    // }

}
