//
//  qqqqInteractor.swift
//  MyFirstApp
//
//  Created by Xiaobei Zhu on 2020/12/25.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol qqqqBusinessLogic {
    // func doSomething(request: qqqq.Something.Request)    
}

protocol qqqqDataStore {
    // var name: String { get set }
}

class qqqqInteractor: qqqqBusinessLogic, qqqqDataStore {
    
    var presenter: qqqqPresentationLogic?
    lazy var worker: qqqqWorker? = {
        return qqqqWorker()
    }()
    
    // MARK: Interactor Methods

    // func doSomething(request: qqqq.Something.Request) {
    //     worker = qqqqWorker()
    //     worker?.doSomeWork()
        
    //     let response = qqqq.Something.Response()
    //     presenter?.presentSomething(response: response)
    // }

}
